export const ambientSoundsTracks = [
  { id: "fragments", title: "Fragments", source: require("../../assets/audio/AmbinetSounds/Ambient -  Fragments.mp3") },
  { id: "instrumental", title: "Instrumental", source: require("../../assets/audio/AmbinetSounds/Ambient -  Instrumental.mp3") },
  { id: "piano", title: "Piano", source: require("../../assets/audio/AmbinetSounds/Ambient -  Piano.mp3") },
  { id: "calm", title: "Calm", source: require("../../assets/audio/AmbinetSounds/Ambient - Calm.mp3") },
  { id: "chillstep", title: "Chillstep", source: require("../../assets/audio/AmbinetSounds/Ambient - Chillstep.mp3") },
  { id: "exploration", title: "Exploration", source: require("../../assets/audio/AmbinetSounds/Ambient - Exploration.mp3") },
  { id: "spiliotis", title: "Spiliotis", source: require("../../assets/audio/AmbinetSounds/Ambient - Spiliotis.mp3") },
  { id: "chill", title: "Chill", source: require("../../assets/audio/AmbinetSounds/Ambinet - Chill.mp3") },
  { id: "fall", title: "Fall", source: require("../../assets/audio/AmbinetSounds/Ambinet - Fall.mp3") },
  { id: "free-ii", title: "Free II", source: require("../../assets/audio/AmbinetSounds/Ambinet - Free II.mp3") },
  { id: "free", title: "Free", source: require("../../assets/audio/AmbinetSounds/Ambinet - Free.mp3") },
  { id: "memories", title: "Memories", source: require("../../assets/audio/AmbinetSounds/Ambinet - Memories.mp3") },
  { id: "memory", title: "Memory", source: require("../../assets/audio/AmbinetSounds/Ambinet - Memory.mp3") },
  { id: "signal", title: "Signal", source: require("../../assets/audio/AmbinetSounds/Ambinet - Signal.mp3") },
  { id: "snowfall", title: "Snowfall", source: require("../../assets/audio/AmbinetSounds/Ambinet - Snowfall.mp3") },
];
