import { StyleSheet } from "react-native";
import {
  navyPrimary,
  navyMuted,
  navyBorder,
  navyAccent,
  brandCard,
} from "../brandColors";
import { layoutConstants } from "../../styles/globalLayoutTablet";

export default StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    minHeight: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: layoutConstants.appBackground,
  },
  visualizationImageWrap: {
    alignSelf: "center",
    marginBottom: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  visualizationImage: {
    width: 10,
    height: 10,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: navyBorder,
    backgroundColor: "rgba(30, 58, 95, 0.06)",
    overflow: "hidden",
  },
  homeButtonContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
    paddingVertical: 16,
  },
  homeButtonContainerTablet: {
    marginTop: 4,
    paddingVertical: 8,
  },
  homeButtonContainerTabletPortrait: {
    marginTop: 0,
    paddingVertical: 4,
  },
  homeButtonTouchable: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: navyBorder,
    backgroundColor: brandCard,
  },
  homeButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: navyMuted,
    marginTop: 4,
  },
  categoryTitle: {
    fontWeight: "700",
    color: navyPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  trackName: {
    fontSize: 18,
    color: navyMuted,
    marginBottom: 24,
    textAlign: "center",
  },
  progressSection: {
    width: "100%",
    maxWidth: 420,
    marginBottom: 12,
  },
  progressBar: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(30, 58, 95, 0.15)",
    marginBottom: 8,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 2,
    backgroundColor: navyAccent,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 0,
  },
  timeText: {
    fontSize: 15,
    color: navyMuted,
  },
  controlsOuterContainer: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: navyBorder,
    backgroundColor: brandCard,
    paddingVertical: 24,
    paddingHorizontal: 20,
    marginBottom: 20,
    width: "100%",
    maxWidth: 420,
    alignItems: "center",
    shadowColor: navyPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  controlsOuterContainerTablet: {
    maxWidth: 520,
  },
  controlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 16,
    flexWrap: "wrap",
  },
  controlsRowTablet: {
    flexWrap: "nowrap",
  },
  controlBtnWrap: {
    alignItems: "center",
  },
  controlIconWrap: {
    justifyContent: "center",
    alignItems: "center",
  },
  controlLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: navyMuted,
    marginTop: 2,
  },
  controlsDivider: {
    width: "100%",
    height: 1,
    backgroundColor: navyBorder,
    marginTop: 12,
    marginBottom: 4,
  },
  controlsFooterRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    marginTop: 12,
  },
  volumeSection: {
    width: "100%",
    maxWidth: "100%",
    alignItems: "flex-start",
    height: 40,
  },
  volumeRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    gap: 10,
    height: 40,
  },
  volumeIconWrap: {
    width: 24,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  volumeTrackWrap: {
    flex: 1,
    height: 40,
    justifyContent: "center",
  },
  volumeTrack: {
    alignSelf: "stretch",
    height: 2,
    borderRadius: 1,
    backgroundColor: "rgba(30, 58, 95, 0.12)",
    overflow: "visible",
  },
  volumeTrackActive: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(30, 58, 95, 0.18)",
  },
  volumeFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 1,
    backgroundColor: navyAccent,
  },
  volumeFillActive: {
    borderRadius: 3,
  },
  volumeThumb: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: navyPrimary,
    marginLeft: -8,
  },
  volumeThumbDefault: {
    top: -7,
  },
  volumeThumbActive: {
    top: -5,
  },
});
