import { StyleSheet } from "react-native";
import { layoutConstants } from "./globalLayoutTablet";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: layoutConstants.appBackground,
    borderRadius: 0,
    borderWidth: 0,
  },

  displayArea: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "flex-start",
    margin: 0,
    padding: 0,
    backgroundColor: layoutConstants.appBackground,
    borderWidth: 0,
    borderRadius: 0,
  },

  displayRoot: {
    flex: 1,
    width: "100%",
    height: "94%",
    alignSelf: "stretch",
    margin: 0,
    padding: 0,
    minHeight: 0,
    maxHeight: "100%",
    borderColor: "orange",
    borderRadius: 20,
    borderWidth: 0,
  },
  dispContTop: {
    flex: 0.4,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 35,
    borderColor: "grey",
    borderRadius: 30,
    borderWidth: 0,
  },
  dispContBottom: {
    flex: 0.6,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "stretch",
    alignSelf: "stretch",
    paddingTop: 0,
    paddingBottom: 8,
    borderColor: "grey",
    borderRadius: 30,
    borderWidth: 0,
  },
  dispContTopCompact: {
    flex: 0.25,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 30,
    borderWidth: 0,
  },
  dispContBottomCompact: {
    flex: 0.75,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "stretch",
    alignSelf: "stretch",
    paddingTop: 0,
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 30,
    borderWidth: 0,
  },
  dispContTopWrapper: layoutConstants.dispContTopWrapper,
  dispFooter: {
    width: "100%",
    height: "6%",
    maxHeight: "100%",
    flexShrink: 0,
    borderWidth: 0,
    borderColor: "orange",
    borderRadius: 20,
  },
  dispFooterCont: {
    flex: 1,
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 3,
    borderColor: "grey",
    borderRadius: 30,
    borderWidth: 0,
  },
});
