import { StyleSheet } from "react-native";

export const layoutConstants = {
  containerPadding: 20,
  cardBorderRadius: 20,
  cardPadding: 24,
  cardPaddingMobile: 16,
  safeAreaBackground: "transparent",
  appBackground: "#f0f0f0",
  cardBackground: "#FF0000",
  dispContTopWrapper: {
    flex: 1,
    minHeight: 0,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 16,
    marginHorizontal: 16,
    padding: 25,
    borderRadius: 35,
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.08)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 5,
  },
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: layoutConstants.appBackground,
    borderRadius: 20,
    borderColor: "brown",
    borderWidth: 0,
  },

  displayArea: {
    flex: 1,
    alignItems: "stretch",
    justifyContent: "flex-start",
    padding: 0,
    backgroundColor: layoutConstants.appBackground,
    borderRadius: 20,
    borderColor: "red",
    borderWidth: 0,
  },

  displayRoot: {
    flex: 1,
    width: "100%",
    height: "94%",
    alignSelf: "stretch",
    padding: 0,
    minHeight: 0,
    maxHeight: "100%",
    borderColor: "orange",
    borderRadius: 20,
    borderWidth: 0,
  },
  dispContTop: {
    flex: 0.4,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 16,
    borderWidth: 0,
  },
  dispContBottom: {
    flex: 0.6,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "stretch",
    alignSelf: "stretch",
    paddingTop: 10,
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 20,
    borderWidth: 0,
  },
  dispContTopCompact: {
    flex: 0.25,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 16,
    borderWidth: 0,
  },
  dispContBottomCompact: {
    flex: 0.75,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "stretch",
    alignSelf: "stretch",
    paddingTop: 0,
    paddingBottom: 0,
    borderColor: "grey",
    borderRadius: 20,
    borderWidth: 0,
  },
  dispContTopWrapper: layoutConstants.dispContTopWrapper,
  dispFooter: {
    width: "100%",
    height: "6%",
    maxHeight: "100%",
    flexShrink: 0,
    borderColor: "orange",
    borderRadius: 20,
    borderWidth: 0,
  },
  dispFooterCont: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "grey",
    borderRadius: 20,
    borderWidth: 0,
  },
});
